variables:
  MAVEN_CLI_OPTS: "--show-version"
cache:
  paths:
    - .m2/repository

building-image:
  stage: build
  before_script:
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_URL'
    - 'mvn versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'
  only:
    - /-release$/
  artifacts:
    paths:
      - target/*.jar

